### ISSUE TITLE
What to do (maybe)

### ISSUE THREAD

**Issue by jeffersonrj14** [NakiriumMC/KillerStick#2]
You might want to review the code to see if it's still working. 
I've left a few comments in the code. Since I'm still learning about Java, I can't be sure if I'm doing it correctly or not, but let me know.

Peace

**Comment by codingjeff01** [comment]
Thank you for putting comments on the code. I appreciate your hard work. Keep going, and I know Java isn't your usual language, but you're trying hard. Thank you.
